CREATE TABLE tasks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  completed boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO tasks (title) VALUES
  ('Plan the week'),
  ('Review project updates'),
  ('Finish the first draft'),
  ('Take a short break');
